name: Mobile CI/CD pipeline

on:
  push:
    branches: [main]

jobs:
  bump-version:
    name: 'Check your KEY'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        
    steps:
  # Show how to print unmasked GitHub secrets to the console
    - name: Step 1 - Echo out a GitHub Actions Secret to the logs
      run: |
        echo "The GitHub Action Secret will be masked:  "
        echo ${{secrets.JWT_REFRESH_TOKEN}}
        echo "Trick to echo GitHub Actions Secret:  "
        echo ${{secrets.JWT_ACCESS_TOKEN}} 
